server:
  port: 8080
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.27.245.194:3306/poetry
    username: admin
    password: qwertyuiop

  redis:
    database: 0
    # Redis服务器地址 写你的ip
#    host: www.amberlake.top
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
#    password: qwertyuiop
    # 连接池最大连接数（使用负值表示没有限制  类似于mysql的连接池
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 表示连接池的链接拿完了 现在去申请需要等待的时间
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒） 去链接redis服务端
    timeout: 6000

  mail:
    host: smtp.163.com
    username: gushiwen0408@163.com
    password: NDFICRCNIZLURART
    from: gushiwen0408@163.com
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            prot: 465
            class: javax.net.ssl.SSLSocketFactory
  servlet:
    multipart:
      max-file-size: 20971520
#      max-request-size: 20971520


#  security:
#    user:
#      name: user
#      password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: false #生成的sql语句大写变小写加下划线（关闭）
#jwt配置（JwtUtil)
poemsys:
  jwt:
    header: Authorization #jwt名称
    expire: 604800  #过期时间（秒）-7天
    secret: fasldfjasd8923ur8uwe9hfs9adiffas  #密钥（随便填够32位就行）

